on:
  schedule:
    - cron: '1 16 * * *'

jobs:
  create-daily-plan-issue:
    runs-on: ubuntu-latest
    name: create daily plan issue
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: create daily plan issue action step
        uses: Leiloloaa/create-daily-plan-issue-action@main
        with:
          token: ${{secrets.TOKEN}}